import type { ReturnRoomTicket } from "./types";

const sharedAssets = [
  {
    id: "asset-mattress",
    name: "Nệm",
    initialCondition: "Tốt",
    quantity: 1,
    handedBy: "Lê Minh",
    handedAt: "2026-01-05",
  },
  {
    id: "asset-keycard",
    name: "Thẻ ra vào",
    initialCondition: "Đã giao",
    quantity: 1,
    handedBy: "Lê Minh",
    handedAt: "2026-01-05",
  },
  {
    id: "asset-ac-remote",
    name: "Remote máy lạnh",
    initialCondition: "Tốt",
    quantity: 1,
    handedBy: "Lê Minh",
    handedAt: "2026-01-05",
  },
];

export const returnRoomTickets: ReturnRoomTicket[] = [
  {
    id: "return-ticket-001",
    code: "PTP001",
    createdAt: "2026-06-18T09:30:00.000Z",
    status: "pendingManagerReview",
    priority: "urgent",
    nextAction: "Lập phiếu thanh toán",
    saleNote: "Khách báo trả phòng sớm, cần kiểm tra tài sản trong ngày.",
    tenant: {
      name: "Nguyễn Văn An",
      phone: "0901 234 567",
      identityNumber: "079201001234",
    },
    contract: {
      code: "HD001",
      startDate: "2026-01-05",
      endDate: "2026-06-20",
      status: "Đang hiệu lực",
      depositAmount: 5000000,
      stayStatus: "Đang lưu trú",
    },
    room: {
      roomCode: "A101",
      bedCode: "Bed 01",
      currentStatus: "Đang ở",
      expectedReturnDate: "2026-06-20",
    },
    handoverAssets: sharedAssets,
    customerConfirmation: {
      status: "notStarted",
    },
    roomFinalization: {
      status: "notStarted",
    },
  },
  {
    id: "return-ticket-002",
    code: "PTP002",
    createdAt: "2026-06-17T15:10:00.000Z",
    status: "pendingManagerReview",
    priority: "normal",
    nextAction: "Lập phiếu thanh toán",
    saleNote: "Khách trả đúng hạn, không ghi nhận yêu cầu đặc biệt.",
    tenant: {
      name: "Trần Bình",
      phone: "0912 456 789",
      identityNumber: "031202009999",
      representative: "Trần Bình",
    },
    contract: {
      code: "HD014",
      startDate: "2026-02-01",
      endDate: "2026-06-21",
      status: "Đang hiệu lực",
      depositAmount: 4200000,
      stayStatus: "Đang lưu trú",
    },
    room: {
      roomCode: "B203",
      bedCode: "Bed 03",
      currentStatus: "Đang ở",
      expectedReturnDate: "2026-06-21",
    },
    handoverAssets: sharedAssets,
    customerConfirmation: {
      status: "notStarted",
    },
    roomFinalization: {
      status: "notStarted",
    },
  },
  {
    id: "return-ticket-003",
    code: "PTP003",
    createdAt: "2026-06-16T11:00:00.000Z",
    status: "waitingAccounting",
    priority: "normal",
    nextAction: "Theo dõi kế toán xử lý",
    saleNote: "Quản lý đã ghi nhận remote máy lạnh hỏng.",
    tenant: {
      name: "Lê Chi",
      phone: "0933 222 111",
      identityNumber: "089203004321",
    },
    contract: {
      code: "HD021",
      startDate: "2026-01-12",
      endDate: "2026-06-22",
      status: "Đang thanh lý",
      depositAmount: 5000000,
      stayStatus: "Đã trả phòng thực tế",
    },
    room: {
      roomCode: "C102",
      bedCode: "Bed 02",
      currentStatus: "Đang chờ kiểm tra",
      expectedReturnDate: "2026-06-22",
    },
    handoverAssets: sharedAssets,
    reconciliation: {
      code: "PDS001",
      status: "Chờ kế toán xử lý",
      hygieneStatus: "passed",
      keycardStatus: "complete",
      hasDamageOrLoss: true,
      managerNotes: "Remote máy lạnh không hoạt động.",
      estimatedDeductions: [
        {
          id: "deduction-remote-estimate",
          description: "Remote máy lạnh hỏng",
          amount: 300000,
          source: "manager",
        },
      ],
    },
    customerConfirmation: {
      status: "notStarted",
    },
    roomFinalization: {
      status: "notStarted",
    },
  },
  {
    id: "return-ticket-004",
    code: "PTP004",
    createdAt: "2026-06-15T08:20:00.000Z",
    status: "accountingResultReady",
    priority: "urgent",
    nextAction: "Ghi nhận khách xác nhận",
    saleNote: "Khách đang chờ kết quả hoàn cọc để rời đi.",
    tenant: {
      name: "Phạm Duy",
      phone: "0988 100 200",
      identityNumber: "052203005555",
    },
    contract: {
      code: "HD031",
      startDate: "2026-03-01",
      endDate: "2026-06-18",
      status: "Đang thanh lý",
      depositAmount: 5000000,
      stayStatus: "Đã trả phòng thực tế",
    },
    room: {
      roomCode: "A204",
      bedCode: "Bed 01",
      currentStatus: "Chờ hoàn tất trả phòng",
      expectedReturnDate: "2026-06-18",
    },
    handoverAssets: sharedAssets,
    reconciliation: {
      code: "PDS002",
      status: "Đã có kết quả tính toán",
      hygieneStatus: "failed",
      keycardStatus: "complete",
      hasDamageOrLoss: true,
      managerNotes: "Phòng cần vệ sinh sâu trước khi mở bán lại.",
      estimatedDeductions: [
        {
          id: "deduction-cleaning-estimate",
          description: "Vệ sinh sâu",
          amount: 250000,
          source: "manager",
        },
      ],
    },
    accountingResult: {
      depositAmount: 5000000,
      refundRate: 70,
      baseRefund: 3500000,
      totalDeductions: 800000,
      finalAmount: 2700000,
      conclusion: "Khách được hoàn cọc",
      deductions: [
        {
          id: "deduction-cleaning",
          description: "Vệ sinh sâu",
          amount: 300000,
          source: "accounting",
        },
        {
          id: "deduction-utility",
          description: "Điện/nước/dịch vụ còn nợ",
          amount: 500000,
          source: "accounting",
        },
      ],
    },
    customerConfirmation: {
      status: "notStarted",
    },
    roomFinalization: {
      status: "notStarted",
    },
  },
  {
    id: "return-ticket-005",
    code: "PTP005",
    createdAt: "2026-06-14T10:45:00.000Z",
    status: "customerConfirmed",
    priority: "normal",
    nextAction: "Cập nhật phòng/giường",
    saleNote: "Khách đã xác nhận qua điện thoại.",
    tenant: {
      name: "Hoàng Mai",
      phone: "0977 888 666",
      identityNumber: "024204006666",
    },
    contract: {
      code: "HD044",
      startDate: "2026-02-14",
      endDate: "2026-06-19",
      status: "Đang thanh lý",
      depositAmount: 4500000,
      stayStatus: "Đã trả phòng thực tế",
    },
    room: {
      roomCode: "D301",
      bedCode: "Bed 04",
      currentStatus: "Chờ cập nhật",
      expectedReturnDate: "2026-06-19",
      beds: [
        { bedCode: "Bed 01", currentStatus: "DANG_THUE", inspectionResult: "DAT" },
        { bedCode: "Bed 02", currentStatus: "DANG_THUE", inspectionResult: "HU_HONG" },
        { bedCode: "Bed 03", currentStatus: "DANG_THUE", inspectionResult: "DAT" },
        { bedCode: "Bed 04", currentStatus: "DANG_THUE", inspectionResult: "DAT" },
      ],
    },
    rentalType: "THUE_GIUONG",
    contractedBedCodes: ["Bed 01", "Bed 02"],
    handoverAssets: sharedAssets,
    reconciliation: {
      code: "PDS003",
      status: "Khách đã xác nhận",
      hygieneStatus: "passed",
      keycardStatus: "complete",
      hasDamageOrLoss: false,
      managerNotes: "Không ghi nhận hư hỏng.",
      estimatedDeductions: [],
    },
    accountingResult: {
      depositAmount: 4500000,
      refundRate: 100,
      baseRefund: 4500000,
      totalDeductions: 0,
      finalAmount: 4500000,
      conclusion: "Khách được hoàn cọc toàn bộ",
      deductions: [],
    },
    customerConfirmation: {
      status: "agreed",
      confirmedAt: "2026-06-19",
    },
    roomFinalization: {
      status: "notStarted",
    },
  },
  {
    id: "return-ticket-006",
    code: "PTP006",
    createdAt: "2026-06-13T13:15:00.000Z",
    status: "needsRecheck",
    priority: "overdue",
    nextAction: "Kiểm tra lại khoản khấu trừ",
    saleNote: "Khách không đồng ý khoản bồi thường chìa khóa.",
    tenant: {
      name: "Võ Gia Hân",
      phone: "0966 333 444",
      identityNumber: "075204007777",
    },
    contract: {
      code: "HD052",
      startDate: "2026-01-20",
      endDate: "2026-06-16",
      status: "Đang thanh lý",
      depositAmount: 3800000,
      stayStatus: "Đã trả phòng thực tế",
    },
    room: {
      roomCode: "B105",
      bedCode: "Bed 02",
      currentStatus: "Chờ kiểm tra lại",
      expectedReturnDate: "2026-06-16",
    },
    handoverAssets: sharedAssets,
    reconciliation: {
      code: "PDS004",
      status: "Cần kiểm tra lại",
      hygieneStatus: "passed",
      keycardStatus: "missing",
      hasDamageOrLoss: false,
      managerNotes: "Khách báo đã trả thẻ cho lễ tân ca tối.",
      estimatedDeductions: [
        {
          id: "deduction-keycard-estimate",
          description: "Thiếu thẻ ra vào",
          amount: 150000,
          source: "manager",
        },
      ],
    },
    accountingResult: {
      depositAmount: 3800000,
      refundRate: 100,
      baseRefund: 3800000,
      totalDeductions: 150000,
      finalAmount: 3650000,
      conclusion: "Khách được hoàn cọc sau khấu trừ",
      deductions: [
        {
          id: "deduction-keycard",
          description: "Thiếu thẻ ra vào",
          amount: 150000,
          source: "accounting",
        },
      ],
    },
    customerConfirmation: {
      status: "disagreed",
      disagreementReason: "Khách báo đã trả thẻ cho lễ tân ca tối.",
    },
    roomFinalization: {
      status: "notStarted",
    },
  },
  {
    id: "return-ticket-007",
    code: "PTP007",
    createdAt: "2026-06-11T16:40:00.000Z",
    status: "completed",
    priority: "normal",
    nextAction: "Không còn hành động bắt buộc",
    saleNote: "Phiếu đã hoàn tất.",
    tenant: {
      name: "Đặng Quốc Việt",
      phone: "0944 900 100",
      identityNumber: "001205008888",
    },
    contract: {
      code: "HD063",
      startDate: "2026-01-01",
      endDate: "2026-06-12",
      status: "Đã thanh lý",
      depositAmount: 4000000,
      stayStatus: "Đã trả phòng",
    },
    room: {
      roomCode: "C205",
      bedCode: "Bed 01",
      currentStatus: "Trống",
      expectedReturnDate: "2026-06-12",
      actualReturnDate: "2026-06-12",
    },
    handoverAssets: sharedAssets,
    reconciliation: {
      code: "PDS005",
      status: "Hoàn tất",
      hygieneStatus: "passed",
      keycardStatus: "complete",
      hasDamageOrLoss: false,
      managerNotes: "Phòng đủ điều kiện mở bán lại.",
      estimatedDeductions: [],
    },
    accountingResult: {
      depositAmount: 4000000,
      refundRate: 100,
      baseRefund: 4000000,
      totalDeductions: 0,
      finalAmount: 4000000,
      conclusion: "Khách được hoàn cọc toàn bộ",
      deductions: [],
    },
    customerConfirmation: {
      status: "agreed",
      confirmedAt: "2026-06-12",
    },
    roomFinalization: {
      status: "available",
      completedAt: "2026-06-12",
      note: "Phòng đã vệ sinh và sẵn sàng bán.",
    },
  },
];
