import type { PaymentSlip } from "./types";

export const paymentSlips: PaymentSlip[] = [
  {
    id: "ptt001",
    code: "PTT001",
    returnTicketCode: "PTP003",
    status: "pendingAccounting",
    createdAt: "2026-06-16T11:00:00.000Z",
    contract: {
      code: "HD001",
      tenantName: "Nguyễn An",
      roomCode: "A101",
      bedCode: "Bed 01",
      depositAmount: 5000000,
      stayDurationMonths: 7,
      stayDescription: "7 tháng",
    },
    managerInspection: {
      hygieneStatus: "Đạt",
      assetStatus: "Hỏng remote máy lạnh",
      estimatedCompensation: 300000,
      note: "Khách làm mất thẻ từ.",
    },
    calculation: {
      refundPolicy: "overSixMonths",
      unpaidRent: 0,
      electricityFee: 250000,
      waterFee: 50000,
      serviceFee: 100000,
      compensationFee: 300000,
      violationPenalty: 0,
      adjustment: 0,
      adjustmentReason: "",
    },
    customerConfirmed: false,
    extraPaymentSlip: { created: false },
  },
  {
    id: "ptt002",
    code: "PTT002",
    returnTicketCode: "PTP004",
    status: "waitingDepositRefund",
    createdAt: "2026-06-15T08:20:00.000Z",
    contract: {
      code: "HD031",
      tenantName: "Trần Bình",
      roomCode: "B203",
      bedCode: "Bed 03",
      depositAmount: 4000000,
      stayDurationMonths: 8,
      stayDescription: "8 tháng",
    },
    managerInspection: {
      hygieneStatus: "Không đạt",
      assetStatus: "Không ghi nhận hư hỏng tài sản",
      estimatedCompensation: 0,
      note: "Phòng cần vệ sinh sâu trước khi mở bán lại.",
    },
    calculation: {
      refundPolicy: "overSixMonths",
      unpaidRent: 0,
      electricityFee: 500000,
      waterFee: 150000,
      serviceFee: 150000,
      compensationFee: 0,
      violationPenalty: 0,
      adjustment: 0,
      adjustmentReason: "",
    },
    customerConfirmed: true,
    extraPaymentSlip: { created: false },
  },
  {
    id: "ptt003",
    code: "PTT003",
    returnTicketCode: "PTP005",
    status: "waitingExtraPayment",
    createdAt: "2026-06-14T10:45:00.000Z",
    contract: {
      code: "HD044",
      tenantName: "Lê Chi",
      roomCode: "C102",
      bedCode: "Bed 02",
      depositAmount: 3000000,
      stayDurationMonths: 4,
      stayDescription: "4 tháng",
    },
    managerInspection: {
      hygieneStatus: "Đạt",
      assetStatus: "Hỏng remote máy lạnh, thiếu thẻ từ",
      estimatedCompensation: 700000,
      note: "Khách đã xác nhận các khoản hư hỏng.",
    },
    calculation: {
      refundPolicy: "underSixMonths",
      unpaidRent: 900000,
      electricityFee: 450000,
      waterFee: 150000,
      serviceFee: 200000,
      compensationFee: 700000,
      violationPenalty: 50000,
      adjustment: -400000,
      adjustmentReason: "Giảm trừ một phần phí bồi thường theo xác nhận quản lý.",
    },
    customerConfirmed: true,
    extraPaymentSlip: {
      created: true,
      code: "PTTT001",
      createdAt: "2026-06-14",
    },
  },
  {
    id: "ptt004",
    code: "PTT004",
    returnTicketCode: "PTP007",
    status: "completedRefund",
    createdAt: "2026-06-11T16:40:00.000Z",
    contract: {
      code: "HD063",
      tenantName: "Đặng Quốc Việt",
      roomCode: "C205",
      bedCode: "Bed 01",
      depositAmount: 4000000,
      stayDurationMonths: 12,
      stayDescription: "Hết hạn hợp đồng",
    },
    managerInspection: {
      hygieneStatus: "Đạt",
      assetStatus: "Đầy đủ",
      estimatedCompensation: 0,
      note: "Phòng đã đủ điều kiện mở bán lại.",
    },
    calculation: {
      refundPolicy: "expiredContract",
      unpaidRent: 0,
      electricityFee: 0,
      waterFee: 0,
      serviceFee: 0,
      compensationFee: 0,
      violationPenalty: 0,
      adjustment: 0,
      adjustmentReason: "",
    },
    customerConfirmed: true,
    extraPaymentSlip: { created: false },
  },
  {
    id: "ptt005",
    code: "PTT005",
    returnTicketCode: "PTP008",
    status: "calculated",
    createdAt: "2026-06-13T13:15:00.000Z",
    contract: {
      code: "HD052",
      tenantName: "Võ Gia Hân",
      roomCode: "B105",
      bedCode: "Bed 02",
      depositAmount: 3800000,
      stayDurationMonths: 6,
      stayDescription: "6 tháng",
    },
    managerInspection: {
      hygieneStatus: "Đạt",
      assetStatus: "Thiếu thẻ ra vào",
      estimatedCompensation: 150000,
      note: "Chờ quản lý báo lại kết quả cho khách.",
    },
    calculation: {
      refundPolicy: "overSixMonths",
      unpaidRent: 0,
      electricityFee: 200000,
      waterFee: 80000,
      serviceFee: 120000,
      compensationFee: 150000,
      violationPenalty: 0,
      adjustment: 0,
      adjustmentReason: "",
    },
    customerConfirmed: false,
    extraPaymentSlip: { created: false },
  },
  {
    id: "ptt006",
    code: "PTT006",
    returnTicketCode: "PTP009",
    status: "noTransaction",
    createdAt: "2026-06-12T10:00:00.000Z",
    contract: {
      code: "HD071",
      tenantName: "Phạm Dũng",
      roomCode: "A201",
      bedCode: "Bed 04",
      depositAmount: 4000000,
      stayDurationMonths: 6,
      stayDescription: "6 tháng",
    },
    managerInspection: {
      hygieneStatus: "Không đạt",
      assetStatus: "Hỏng đèn led",
      estimatedCompensation: 200000,
      note: "Khách đồng ý các khoản trừ.",
    },
    calculation: {
      refundPolicy: "overSixMonths",
      unpaidRent: 0,
      electricityFee: 2200000,
      waterFee: 200000,
      serviceFee: 200000,
      compensationFee: 200000,
      violationPenalty: 0,
      adjustment: 0,
      adjustmentReason: "",
    },
    customerConfirmed: true,
    extraPaymentSlip: { created: false },
  },
  {
    id: "ptt007",
    code: "PTT007",
    returnTicketCode: "PTP010",
    status: "needReview",
    createdAt: "2026-06-10T14:30:00.000Z",
    contract: {
      code: "HD082",
      tenantName: "Nguyễn Kim Ngân",
      roomCode: "C302",
      bedCode: "Bed 01",
      depositAmount: 5000000,
      stayDurationMonths: 2,
      stayDescription: "2 tháng",
    },
    managerInspection: {
      hygieneStatus: "Đạt",
      assetStatus: "Bể gương nhà tắm",
      estimatedCompensation: 1500000,
      note: "Khách không đồng ý khoản bồi thường bể gương.",
    },
    calculation: {
      refundPolicy: "underSixMonths",
      unpaidRent: 0,
      electricityFee: 300000,
      waterFee: 100000,
      serviceFee: 200000,
      compensationFee: 1500000,
      violationPenalty: 0,
      adjustment: 0,
      adjustmentReason: "",
    },
    customerConfirmed: false,
    extraPaymentSlip: { created: false },
  },
];
